# -*- coding: utf-8 -*-

eventNameMap = {
    "Left Foot Strike": "LHS",
    "Left Foot Off": "LTO",
    "Right Foot Strike": "RHS",
    "Right Foot Off": "RTO",
}

sigNameMap = {
    'L_FLAT': '',
    'LAbsAnkleAngle': '',
    'LAJC': '',
    'LANA': '',
    'LANK': '',
    'LAnkleAngles': 'Left Ankle Angles',
    'LAnkleAnglesKFunc': '',
    'LAnkleForce': '',
    'LAnkleMoment': 'Left Ankle Moment',
    'LAnkleMomentKFunc': '',
    'LAnklePower': 'Left Ankle Power',
    'LAnklePowerKFunc': '',
    'LArchHeight': 'Left Arch Height',
    'LArchHeightIndex': '',
    'LASI': '',
    'LBelfastPelvisAngles': '',
    'LCPG': '',
    'LD1M0': '',
    'LD5M': '',
    'LFEA': '',
    'LFEL': '',
    'LFEO': '',
    'LFEP': '',
    'LFETBA': '',
    'LFFHFA': '',
    'LFFTBA': '',
    'LFOA': '',
    'LFOF0': '',
    'LFOF1': '',
    'LFOF2': '',
    'LFOF3': '',
    'LFOL': '',
    'LFOO': '',
    'LFootProgressAngles': 'Left Foot Progression',
    'LFootProgressAnglesKFunc': '',
    'LFOP': '',
    'LFTA': '',
    'LGroundReactionForce': '',
    'LGroundReactionMoment': '',
    'LHDF0': '',
    'LHDF1': '',
    'LHDF2': '',
    'LHDF3': '',
    'LHE1': '',
    'LHEE': '',
    'LHFB': '',
    'LHFB_ocst': '',
    'LHFTBA': '',
    'LHFTFL': '',
    'LHipAngles': 'Left Hip Angles',
    'LHipAnglesFunc': '',
    'LHipAnglesHarrington': '',
    'LHipForce': '',
    'LHipForceFunc': '',
    'LHipMoment': 'Left Hip Moment',
    'LHipMomentFunc': '',
    'LHipPower': 'Left Hip Power',
    'LHipPowerFunc': '',
    'LHJC': '',
    'LHJCHarrington': '',
    'LHLX': '',
    'LHLX0': '',
    'LHLX1': '',
    'LHLX2': '',
    'LHLX3': '',
    'LHPA': '',
    'LHXFFA': '',
    'LISH': '',
    'LKJCFunc': '',
    'LKNA': '',
    'LKNE': '',
    'LKneeAngles': 'Left Knee Angles',
    'LKneeAnglesFunc': '',
    'LKneeAnglesHarrington': '',
    'LKneeForce': '',
    'LKneeForceFunc': '',
    'LKneeMoment': 'Left Knee Moment',
    'LKneeMomentFunc': '',
    'LKneePower': 'Left Knee Power',
    'LKneePowerFunc': '',
    'LLCA': '',
    'LNormalisedGRF': 'Left GRF',
    'LP1M': '',
    'LP5M': '',
    'LPelvisAngles': 'Left Pelvic Angles',
    'LPROXFF': '',
    'LShank_LThigh_sara': '',
    'LShank_LThigh_score': '',
    'LShankA': '',
    'LShankL': '',
    'LShankO': '',
    'LShankP': '',
    'LSHN': '',
    'LSHN_ocst': '',
    'LSTL': '',
    'LTHA1': '',
    'LTHA1_ocst': '',
    'LTHA2': '',
    'LTHA2_ocst': '',
    'LTHI': '',
    'LTHI_ocst': '',
    'LThigh_LShank_sara': '',
    'LThigh_LShank_score': '',
    'LThighA': '',
    'LThighL': '',
    'LThighO': '',
    'LThighP': '',
    'LTHL': '',
    'LTHL_ocst': '',
    'LTIA': '',
    'LTIB': '',
    'LTIB1': '',
    'LTIB2': '',
    'LTIB3': '',
    'LTIB_ocst': '',
    'LTIBA': '',
    'LTIL': '',
    'LTIO': '',
    'LTIP': '',
    'LTOA': '',
    'LTOE': '',
    'LTOL': '',
    'LTOO': '',
    'LTOP': '',
    'LTUB': '',
    'LTUB_ocst': '',
    'PEL0': '',
    'PELA': '',
    'PELAng': '',
    'PELL': '',
    'PELO': '',
    'PELP': '',
    'R_FLAT': '',
    'RAbsAnkleAngle': '',
    'RAJC': '',
    'RANA': '',
    'RANK': '',
    'RAnkleAngles': 'Right Ankle Angles',
    'RAnkleAnglesKFunc': '',
    'RAnkleForce': '',
    'RAnkleMoment': 'Right Ankle Moment',
    'RAnkleMomentKFunc': '',
    'RAnklePower': 'Right Ankle Power',
    'RAnklePowerKFunc': '',
    'RArchHeight': '',
    'RArchHeightIndex': '',
    'RASI': '',
    'RBelfastPelvisAngles': '',
    'RCPG': '',
    'RD1M0': '',
    'RD5M': '',
    'RFEA': '',
    'RFEL': '',
    'RFEO': '',
    'RFEP': '',
    'RFETBA': '',
    'RFFHFA': '',
    'RFFTBA': '',
    'RFOA': '',
    'RFOF0': '',
    'RFOF1': '',
    'RFOF2': '',
    'RFOF3': '',
    'RFOL': '',
    'RFOO': '',
    'RFootProgressAngles': 'Right Foot Progression',
    'RFootProgressAnglesKFunc': '',
    'RFOP': '',
    'RFTA': '',
    'RGroundReactionForce': '',
    'RGroundReactionMoment': '',
    'RHDF0': '',
    'RHDF1': '',
    'RHDF2': '',
    'RHDF3': '',
    'RHE1': '',
    'RHEE': '',
    'RHFB': '',
    'RHFB_ocst': '',
    'RHFTBA': '',
    'RHFTFL': '',
    'RHipAngles': 'Right Hip Angles',
    'RHipAnglesFunc': '',
    'RHipAnglesHarrington': '',
    'RHipForce': '',
    'RHipForceFunc': '',
    'RHipMoment': 'Right Hip Moment',
    'RHipMomentFunc': '',
    'RHipPower': 'Right Hip Power',
    'RHipPowerFunc': '',
    'RHJC': '',
    'RHJCHarrington': '',
    'RHLX': '',
    'RHLX0': '',
    'RHLX1': '',
    'RHLX2': '',
    'RHLX3': '',
    'RHPA': '',
    'RHXFFA': '',
    'RISH': '',
    'RKJCFunc': '',
    'RKNA': '',
    'RKNE': '',
    'RKneeAngles': 'Right Knee Angles',
    'RKneeAnglesFunc': '',
    'RKneeAnglesHarrington': '',
    'RKneeForce': '',
    'RKneeForceFunc': '',
    'RKneeMoment': 'Right Knee Moment',
    'RKneeMomentFunc': '',
    'RKneePower': 'Right Knee Power',
    'RKneePowerFunc': '',
    'RLCA': '',
    'RNormalisedGRF': 'Right GRF',
    'RP1M': '',
    'RP5M': '',
    'RPelvisAngles': 'Right Pelvic Angles',
    'RPROXFF': '',
    'RShank_RThigh_sara': '',
    'RShank_RThigh_score': '',
    'RShankA': '',
    'RShankL': '',
    'RShankO': '',
    'RShankP': '',
    'RSHN': '',
    'RSHN_ocst': '',
    'RSTL': '',
    'RTHA1': '',
    'RTHA1_ocst': '',
    'RTHA2': '',
    'RTHA2_ocst': '',
    'RTHI': '',
    'RTHI_ocst': '',
    'RThigh_RShank_sara': '',
    'RThigh_RShank_score': '',
    'RThighA': '',
    'RThighL': '',
    'RThighO': '',
    'RThighP': '',
    'RTHL': '',
    'RTHL_ocst': '',
    'RTIA': '',
    'RTIB': '',
    'RTIB1': '',
    'RTIB2': '',
    'RTIB3': '',
    'RTIB_ocst': '',
    'RTIBA': '',
    'RTIL': '',
    'RTIO': '',
    'RTIP': '',
    'RTOA': '',
    'RTOE': '',
    'RTOL': '',
    'RTOO': '',
    'RTOP': '',
    'RTUB': '',
    'RTUB_ocst': '',
    'SACR': ''
}

emgNameMap = {
    'L Gast': 'Left Gastrocnemius',
    'L Hams': 'Left Hamstrings',
    'L Rect': 'Left Rectus Femoris',
    'L Spare': '',
    'L Tib Ant': 'Left Tibialis Anterior',
    'L Tib Post': 'Left Tibialis Posterior',
    'R Gast': 'Right Gastrocnemius',
    'R Hams': 'Right Hamstrings',
    'R Rect': 'Right Rectus Femoris',
    'R Spare': '',
    'R Tib Ant': 'Right Tibialis Anterior',
    'R Tib Post': 'Right Tibialis Posterior',
}
